pipeline {
    agent any

    environment {
        // Usar el ID de la credencial, 
        VERCEL_TOKEN = credentials('vercel-token')
    }

    stages {
        stage('Clonar repositorio') {
            steps {
                git credentialsId: 'b188154a-b5db-4823-81d6-c2fe7f033e16',
                    url: 'https://github.com/AlejaRosero/chimayoy.git',
                    branch: 'main'
            }
        }

        stage('Instalar dependencias') {
            steps {
                bat 'npm install'
            }
        }

        stage('Build del proyecto') {
            steps {
                bat 'npm run build'
            }
        }

        stage('Desplegar en Vercel') {
            steps {
                bat "vercel --token=%VERCEL_TOKEN% --prod --yes"
            }
        }
    }

    post {
        success {
            echo '✅ Despliegue exitoso en Vercel.'
        }
        failure {
            echo '❌ Falló el despliegue. Revisa los logs.'
        }
    }
}
